on:
  workflow_call:
    inputs:
      build-type:
        type: string
        required: true
    outputs:
      filename:
        description: "artifact file name"
        value: ${{ jobs.build-api.outputs.filename }}
    secrets:
      key-alias:
        required: false
      keystore:
        required: false
      key-password:
        required: false

jobs:
  build-apk:
    runs-on: ubuntu-latest
    outputs:
      filename: ${{ steps.set_output.outputs.filename }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up OpenJDK 17
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "17"
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
      - name: Install required platform
        run: sdkmanager "platforms;android-33" "build-tools;33.0.2"
      - name: Replace android.jar
        run: |
          curl -L https://github.com/Reginer/aosp-android-jar/raw/main/android-33/android.jar > /usr/local/lib/android/sdk/platforms/android-33/android.jar
      - name: Build debug APK
        if: ${{ inputs.build-type == 'debug' }}
        run: ./gradlew assemble
      - name: Build release APK
        if: ${{ inputs.build-type == 'release' }}
        run: ./gradlew assembleRelease
      - name: Save keystore as file
        run: echo "${KEYSTORE_B64}" | base64 -d > keystore.jks
        env:
          KEYSTORE_B64: ${{ secrets.keystore }}
      - name: align APK with zipalign
        run: $ANDROID_SDK_ROOT/build-tools/33.0.2/zipalign -v -p 4 app/build/outputs/apk/${BUILD_TYPE}/app-${BUILD_TYPE}-unsigned.apk app-${BUILD_TYPE}-unsigned-aligned.apk
        env:
          BUILD_TYPE: ${{ inputs.build-type }}
      - name: Sign APK
        if: ${{ inputs.build-type == 'release' }}
        run: echo "${KEY_PASSWORD}" | $ANDROID_SDK_ROOT/build-tools/33.0.2/apksigner sign --ks keystore.jks --ks-key-alias "${KEY_ALIAS}" --key-pass "env:KEY_PASSWORD" --out dev.bluehouse.enablevolte.apk app-${BUILD_TYPE}-unsigned-aligned.apk
        env:
          KEY_ALIAS: ${{ secrets.key-alias }}
          KEY_PASSWORD: ${{ secrets.key-password }}
          BUILD_TYPE: ${{ inputs.build-type }}
      - name: Rename APK
        if: ${{ inputs.build-type != 'release' }}
        run: mv app-${BUILD_TYPE}-unsigned-aligned.apk dev.bluehouse.enablevolte.apk
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: "${{ github.run_id }}-APK"
          path: dev.bluehouse.enablevolte.apk
          retention-days: 3
      - id: set_output
        run: echo "filename=${{ github.run_id }}-APK" >> $GITHUB_OUTPUT
